### ISSUE TITLE
umich.ms.fileio.exceptions.FileParsingException for TripleTof data

### ISSUE THREAD

**Issue by JB91451** [Nesvilab/MSFragger#63] opened 2020-03-10 10:23 UTC
Dear Fengchao,

I'm not completely sure if this is the right forum for the following question but database searches with MSFragger are the point where the error manifests:

I measured some samples on a SciEx TripleTof 5600+ which generates a pair of vendor specific files (.wiff and .wiff.scan). When searching these files they first have to be converted to e.g. the mzml format. Different options are available for this and I usually use msconvert with the vendor supplied algorithms. An alternative method is to use a SciEx provided converter that, unfortunately, does not run on win10 maschines anymore. Within the latter converter there are the options to use either a fast mode for peak picking called "-centroid" or to use a mode that should be identical to the vendors propriatary search engines mode, called therefore "-proteinpilot".
The problem is that occasionally when a file was converted with msconvert or the "-centroid" option, MSFragger fails during the initial search with the error message copied below. However, this error does not happen when the "-proteinpilot" option was selected and I think therefore this should not be a problem with the original file but rather something during the conversion with the other options or a problem with the handling of some kind of information in the mzml file. Also, I noted that the failing scan has a different number when the conversion is done with msconvert or with the SciEx file converter. 

Best regards,
Juergen

Error message:
(copied from the FragPipe output)
...
Selected fragment tolerance 0.10 Da.
18576276 fragments to be searched in 1 slices (0.28 GB total)
Operating on slice 1 of 1: 
	001. 200305_TF1_PWende_JB_TH_Minus_N_MMazei_InSolDig_unfractionated_180min_bRP_01.mzml Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.simontuffs.onejar.Boot.run(Boot.java:340)
	at com.simontuffs.onejar.Boot.main(Boot.java:166)
Caused by: umich.ms.fileio.exceptions.FileParsingException: When trying to set parent for Scan #43094, the precursor (PrecursorInfo) field was null, which should not happen.

	at umich.ms.datatypes.scancollection.ScanCollectionHelper.finalizeScanCollection(ScanCollectionHelper.java:160)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:852)
	at umich.ms.datatypes.scancollection.impl.ScanCollectionDefault.loadData(ScanCollectionDefault.java:788)
	at edu.umich.andykong.msfragger.b.a(Unknown Source)
	at edu.umich.andykong.msfragger.b.a(Unknown Source)
	at edu.umich.andykong.msfragger.z.a(Unknown Source)
	at edu.umich.andykong.msfragger.x.<init>(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.b(Unknown Source)
	at edu.umich.andykong.msfragger.MSFragger.main(Unknown Source)
	... 6 more
Process 'MsFragger' finished, exit code: 1
...

**Comment by chhh** [comment] 2020-03-11 18:26
@JB91451 Could you please share the mzml file in question?

**Comment by JB91451** [comment] 2020-03-11 18:36
Dear Dimitry,

yes of course. Could you open me a box folder?

**Comment by chhh** [comment] 2020-03-11 20:58
@JB91451 What's your email? Required to send invitation

**Comment by JB91451** [comment] 2020-03-12 15:41
I have send you an email. Did you receive it?

**Comment by fcyu** [comment] 2020-03-16 14:54
@JB91451 I can see that you are already the Editor of the shared Box folder but there is no file.

Best,

Fengchao

**Comment by JB91451** [comment] 2020-03-16 17:21
Sorry for the late reply. I was on a prolonged weekend and had no internet access during that time. I just started the file upload and it shoud be finished soon. There are two files: 
"..._proteinpilot_01.mzml" should work while the other file results in the error above. Both files were converted from the same measurement with difference just in the peak finding / centroiding algorithm.

**Comment by chhh** [comment] 2020-03-26 20:53
@JB91451 
Looks like fragger behavior is more or less correct in this case. The big file (not proteinpilot) has a scan:
**\<spectrum id="sample=1 period=1 cycle=2058 experiment=2" defaultArrayLength="1121" index="43198">**
The important part for us here is the id:
- "sample=1 period=1 cycle=2058 experiment=2"

Proteinpilot file does NOT have this scan. It has neighboring ones:
- "sample=1 period=1 cycle=2058 experiment=1"
- "sample=1 period=1 cycle=2058 experiment=3"

The problem with this scan is it's an MS2 scan, but it does not list any precursor information. It only says that it's an positive centroided MS2 scan with m/z range 100-1600.
Our reader complained about it, while "proteinpilot", I guess, has silently discarded those scans.

There is a huge number of those scans without precursor info,  just tested it - 18805/20820 MS2 scans had no precursor info.
That explains why the "proteinpilot" file is so small in in comparison.

Is this some sort of special acquisition? Like maybe fragmenting all ions at once (Waters has such a thing, I think) instead of isolating narrower mz bands? These scans start at 65.83min and they are always "experiment=2" in Sciex scan terms and they repeat on average every 3.4 seconds.

In any case something is wrong with the converter, as it still should report activation and isolation range of ions that underwent fragmentation.

**Comment by JB91451** [comment] 2020-03-27 06:21
Dear Dimitry,

Thank you for checking this so thoroughly. Theoretically the SciEx intrument can fragment larger ranges at once (called SWATH mode) but in these samples I certainly did not use the option. Also it could only be switched on or off for the complete measurement; not for a particular scan or time window.

If the proteinpilot algorithm discards these scans this could explain the rather low ID rate I have for some files. In any case, I will try to find this scan in the original file with the native Sciex viewer. Perhaps I can find something unusual about the precursor there.
Unfortunately this will last a while as we currently have to work at home and therefore I have very limited access to my data.

Best regards,
Juergen

**Comment by JB91451** [comment] 2020-04-03 08:14
Dear Dimitry,

meanwhile I could check the original file. The missing precursor information originates in this file. So I guess, I have to contact the companies customer support to figure out, how this can happen.

Thank you again for your affords,
Juergen

**Comment by chhh** [comment] 2020-04-03 08:20
@JB91451 Hi Juergen,
Do I get it right that you have confirmed with their viewer (or somehow else) that the original file was missing precursor info?

**Comment by JB91451** [comment] 2020-04-03 08:49
Yes, I tested it with their viewer (Peakview) and there is no information about the precursor for the first MS2 scan in the cycle starting at about 65.83 min (and in the following cylces as well; unfortunately SciEx does not display any scan numbers). However, the second+ MS2 scans have their precursor correctly assigned again. And also cycles before that time, the precursor information is present for all MS2 scans.

**Comment by anesvi** [comment] 2020-04-03 14:38
I suggest you use Proteowizard converter to get mzML files that way. We do not have the bandwith to chase issues with ABSciex converter.
Best
Alexey

**Comment by JB91451** [comment] 2020-04-03 15:30
Dear Alexey,

Thank you for your comment. I already tried with msconvert. However, the results were the same. Since Dimitry pointed me to the missing precursor information, I checked the original wiff/wiff.scan file with Peakview and indeed found that the precursor information was missing for some scans from the beginning. I will therefore contact Sciex support.

Thank you again,
Juergen

**Comment by anesvi** [comment] 2020-04-03 15:36
Ok, thanks. I understand the issue better now.
I just know that Dave Tabb had some issues with ABSciex converter and MSFragger, but for him using mzML from Proteowizard seemed to solve it. I guess your issue is different. Good luck resolving it with Sciex folks.
Best
Alexey

**Comment by fcyu** [comment] 2020-04-03 19:41
Looks like the issue is out of the scope: it's ABSciex's issue. I close it.

**Closed by fcyu** 2020-04-03 19:41 UTC

**Comment by chhh** [comment] 2020-04-04 06:11
That was in the initial design of the reader library - to throw exceptions (java speak for: show errors) when weird situations occur rather than swallow them silently so that the users don't know anything was wrong with the original file.
