### ISSUE TITLE
ID rate report

### ISSUE THREAD

**Issue by avera1988** [Nesvilab/MSFragger#159] opened 2021-05-26 13:05 UTC
Hello,

We are running MSFragger in a command-line flavor, and would like to know our peptide identification rate (ID rate), is there any way we can obtain this info from MSfragger results?

Thank you in advance.

Arturo.

**Comment by fcyu** [comment] 2021-05-26 15:01
Hi Arturo,

The result from MSFragger is unfiltered. You need to use Philosopher to estimate the FDR and filter PSMs. You can try [FragPipe](https://fragpipe.nesvilab.org/).

Best,

Fengchao

**Comment by avera1988** [comment] 2021-05-26 15:21
Hi Fengchao,

Thank you for answering. I already ran all steps on Philosopher (Peptideprophet, Proteinprophet, Filter, and Report). Now I am wondering if there is any file with the % ID Rate or do I need to calculate it manually, so far I was unable to locate any file showing this information. 

I hope you can help us.

Best!

Arturo.

**Comment by fcyu** [comment] 2021-05-26 15:26
Hi Arturo,

Thanks for your clarification. 

If you have run Philosopher, all of the entries in psm.tsv are filtered with 1% FDR. Currently, we do not have any file directly reports the ID rate. You have to calculate it by yourself. We have discussed generating a summary file internally and are working on it.

Best,

Fengchao

**Comment by fcyu** [comment] 2021-05-26 15:28
Closed because it is duplicate of https://github.com/Nesvilab/FragPipe/issues/200.

**Closed by fcyu** 2021-05-26 15:28 UTC

**Comment by avera1988** [comment] 2022-05-11 10:49
Hello again,

We develop a script to calculate the IDrates after Fragpipe runs either by GUI or CLI  using MSFragger-Philosopher-IonQuant, it basically takes the MSFragger/Fargpipe output logfile and looks for the number of scans e.g. ```20210128_IA_R15.raw: Scans = 35143```  then it will look for the number of psm on each sample after Philosopher-IonQuant calculation using the  ```psm.tsv``` file IonQuant produces, where each row represents a PSM for that sample. Then using the formula ```IDRate=PSM/MSScans``` we calculate the IDrate for that particular sample. This have been working well for samples obtained by Q-exactive .raw files, however, nowadays we are working with samples  from timsTOF PASEF and we noticed that at the time MSFragger reads the file it prints certain number of scans ```20220302_B1_Slot1-13_1_1598.d: Scans = 38188``` but when I try to obtain the number of PSM for this sample the number is higher than the total number o scans: ```cat 20220302_B1_Slot1-13_1_1598.psm.tsv |awk 'NR>1 && NF=1'|cut -f 1|wc -l = 46633``` . We are wondering how MSFragger extracts the number of Scans? I found that if I count the number of "spectrum" for that sample ```20220302_B1_Slot1-13_1_1598``` in the .pepXML result from MSFragger the number is 129669, which seems to be more logical than the 38188 scans, but We are having a hard time trying to figure it out how to use the information from MSFragger/FragPipe to calculate the IDRate for each sample, and are wondering if you could give us a hint on the best way to do this.

Thank you in advance.

Arturo

**Comment by fcyu** [comment] 2022-05-11 13:24
Hi Arturo,

For ddaPASEF data it is a little bit tricky. The scans we reported in the log is the number of MS2 frames. While in the search, Bruker's library reports multiple MS2 "scans" for each MS2 frames because there are multiple precursors in one frame. We don't report the number of MS2 "scans" in the first place because it takes a long time to get them.

Best,

Fengchao

**Comment by avera1988** [comment] 2022-05-11 16:59
Hi Fengchao,

Thanks a lot for the qucikly reply. I understand, do you think I can use the _uncalibrated.mgf or the _calibrated.mgf to extract the number of spectra ?  I found that this file has:

```BEGIN IONS
TITLE=20220302_B1_Slot1-13_1_1598.1.1.2
CHARGE=2+
RTINSECONDS=7.348257154226303
PEPMASS=608.2972563589042 2511.0`
```

Is the TITLE the spectra? If so I can parse this file and calculate the total number of MS/MS in the experiment.

Thank you!

Arturo.
